name: Publish to PyPI

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      target:
        description: 'Publish target'
        required: true
        default: 'testpypi'
        type: choice
        options:
          - testpypi
          - pypi

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    
    - name: Install build dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build twine
    
    - name: Build voice-mcp package
      run: python -m build
    
    - name: Check voice-mcp package
      run: twine check dist/*
    
    - name: Build voice-mode package
      run: |
        # Clean previous build
        rm -rf dist/
        # Swap pyproject files
        mv pyproject.toml pyproject-voice-mcp.toml.tmp
        cp pyproject-voice-mode.toml pyproject.toml
        # Build voice-mode
        python -m build
        # Restore original
        mv pyproject-voice-mcp.toml.tmp pyproject.toml
        # Move voice-mode artifacts to separate directory
        mkdir -p dist-voice-mode
        mv dist/* dist-voice-mode/
        # Rebuild voice-mcp for publishing
        python -m build
    
    - name: Check voice-mode package
      run: twine check dist-voice-mode/*
    
    - name: Publish voice-mcp to TestPyPI
      if: github.event_name == 'workflow_dispatch' && inputs.target == 'testpypi'
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.TEST_PYPI_API_TOKEN }}
      run: twine upload --repository testpypi dist/*
    
    - name: Publish voice-mode to TestPyPI
      if: github.event_name == 'workflow_dispatch' && inputs.target == 'testpypi'
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.TEST_PYPI_API_TOKEN }}
      run: twine upload --repository testpypi dist-voice-mode/*
    
    - name: Publish voice-mcp to PyPI
      if: (github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')) || (github.event_name == 'workflow_dispatch' && inputs.target == 'pypi')
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
      run: twine upload dist/*
    
    - name: Publish voice-mode to PyPI
      if: (github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')) || (github.event_name == 'workflow_dispatch' && inputs.target == 'pypi')
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
      run: twine upload dist-voice-mode/*